apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ruby-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dprateek1991/app-deployment.git
    targetRevision: main
    path: helm-chart
    helm:
      valueFiles: 
      - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ruby-app
  syncPolicy:
    automated:
      selfHeal: true
      prune: false 