apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.name }}
  labels:
    name: {{ .Values.name }}
    app: {{ .Values.name }}
spec:  
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: {{ .Values.name }}